
<?php if(!is_loggedIn()): ?>
<div class="box" style="margin-top:7px">
    <div class="title"><?php _lang('login')?></div>
    <div class="box-content">
        <form action="<?php echo url_to_pager('login')?>" method="post">
            <fieldset class="form-group"><input type="text" class="form-control form-control-lg" name="val[username]"  placeholder="<?php _lang('username-email-address')?>"></fieldset>
            <fieldset class="form-group"><input type="password" class="form-control form-control-lg" name="val[password]" placeholder="<?php _lang('your-password')?>"></fieldset>
            <div class="clearfix">
                <div class="checkbox pull-left">
                    <label class="c-input c-checkbox">
                        <input name="val[remember]" checked type="checkbox">
                        <span class="c-indicator"></span>
                        <?php _lang('remember-me')?>
                    </label>
                </div>
                <a ajax="true" href="<?php echo url_to_pager('forgot-password')?>" class="pull-right"><?php _lang('forgot-password')?></a>
            </div>
            <button class="btn btn-info btn-block btn-upper"><?php _lang('sign-in')?></button>
        </form>
    </div>
</div>
<?php endif ?>