<div class="contact">
    <?php if($message): ?>
    <div class="alert alert-success"><?php echo lang('contact::message-submitted')?></div>
    <?php endif ?>
    <p><?php echo lang('contact::fill-the-form-below-to-contact-us')?></p>
    <form action="" method="post">
        <input name='val[sent_date]' type="hidden" value="<?php echo date ('M'); ?> <?php echo date ('d'); ?>">
        <input name='val[sent_year]' type="hidden" value="<?php echo date ('Y'); ?>">
    <p>
        <label><?php echo lang('contact::name')?></label>
        <input name='val[name]' type="text" required="">
    </p>



        <p>
            <label><?php echo lang('contact::email')?>:</label>
            <input name='val[email]' type="email" required="">
        </p>

        <p>
            <label><?php echo lang('contact::subject')?>:</label>
            <input name='val[subject]' type="text" required="">
        </p>

        <p>
            <label><?php echo lang('contact::message')?>:</label>
            <textarea name='val[message]' required=""></textarea>
        </p>



<!--
        <?php if(get_setting("enable-captcha")):?>
            <?php if(get_setting("enable-captcha") == '1'):?>
                <div class="row">
                    <div class="col-md-6">
                        <input class="form-control" type="text" placeholder="<?php _lang('enter-text-below')?>" name="val[captcha]" id="captcha-input"/>
                    </div>
                    <div class="col s6">
                        <img id="captcha-image" src="<?php echo url("captcha.php")?>"/>
                        <a style="position: relative;bottom: 10px" href="javascript:void(0)" onclick="document.getElementById('captcha-image').src='<?php echo url('captcha.php')?>?'+Math.random();
                            document.getElementById('captcha-input').focus();
                            "><i class="ion-ios-reload"></i></a><br/>
                    </div>
                </div>

            <?php else:?>
                <div class="g-recaptcha" data-sitekey="<?php echo config('recaptcha-key'); ?>"></div>
                <script type="text/javascript"
                        src="https://www.google.com/recaptcha/api.js?hl=en">
                </script>
            <?php endif?>
        <?php endif?>
-->
        <p align="center" class="submit">
            <button style="margin-top: 20px" type="submit" name="reply" class="btn btn-info"><?php _lang('submit')?> </button>
        </p>
        </form>
    </div>