<div class="wrapper">


    <!------Mailbox Starts------>
    <div style="">
        <!-- Main content -->
        <section class="content">
            <div class="row">



                <!------Hidden start---->
                <div class="col-md-3" style="display:none">
                    <a href="mailbox.html" class="btn btn-primary btn-block margin-bottom">Back to Inbox</a>

                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <h3 class="box-title">Folders</h3>

                            <div class="box-tools">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="ion fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body no-padding">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="mailbox.html"><i class="ion fa-inbox"></i> Inbox
                                        <span class="label label-primary pull-right">12</span></a></li>
                                <li><a href="#"><i class="ion ion-android-mail"></i> Sent</a></li>
                                <li><a href="#"><i class="ion fa-file-text-o"></i> Drafts</a></li>
                                <li><a href="#"><i class="ion fa-filter"></i> Junk <span class="label label-warning pull-right">65</span></a>
                                </li>
                                <li><a href=""><i class="ion ion-ios-trash-outline"></i> Trash</a></li>
                            </ul>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /. box -->
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <h3 class="box-title">Labels</h3>

                            <div class="box-tools">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="ion fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body no-padding">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#"><i class="ion fa-circle-o text-red"></i> Important</a></li>
                                <li><a href="#"><i class="ion fa-circle-o text-yellow"></i> Promotions</a></li>
                                <li><a href="#"><i class="ion fa-circle-o text-light-blue"></i> Social</a></li>
                            </ul>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!------Hidden end---->





                <?php foreach($contacts as $contact):?>

                    <!-- /.col -->
                    <div class="message_reply">

                        <?php if($message): ?>
                            <div class="alert alert-success"><?php echo $message ?></div>
                        <?php endif ?>
                        <div class="box box-primary">
                            <div class="box-header with-border">
                            </div>
                            <!-- /.box-header -->


                            <form action="" method="post">



                                <div class="box-body">



                                    <div class="form-group">
                                        <input class="form-control" name='val[email]' style="font-style:italic" value="<?php echo lang('contact::to')?>: <?php echo $contact['email'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <input name='val[subject]' class="form-control" style="font-weight:bold" placeholder="<?php echo lang('contact::subject')?>:" value="<?php echo lang('contact::re')?>: <?php echo $contact['subject'] ?>">
                                    </div>
                                    <div class="form-group">

                                        <textarea name='val[message]' class="ckeditor" style="height: 200px">
                                            <div style="height:30px;">

                                            </div>
                                            <hr>
                                            <div style="padding: 0 1.5% 0.5% 1.5%"> <?php echo $contact['message'] ?></div>
                                        </textarea>



                                    </div>
									<!--
                                    <div class="form-group">
                                        <div class="btn btn-default btn-file" style="width:18%;height:2.3em">
                                            <i class="ion fa-paperclip"></i> Attachment
                                            <input type="file" name="attachment" style="margin-top:-100%">
                                        </div>
                                        <p class="help-block">Max. 32MB</p>
                                    </div>
									-->
                                </div>
                                <!-- /.box-body -->
                                <div class="box-footer">
                                    <div class="pull-right">
                                       <!-- <button type="button" class="btn btn-default"><i class="ion fa-pencil"></i> Draft</button> -->

                                        <button type="submit" class="btn btn-primary"><i class="ion ion-android-mail"></i> <?php echo lang('contact::send')?></button>
                                    </div>
									</form>
                                     <form method="post" action="delete">
                                        <input type="hidden" name="contact_id" value="<?php echo $contact['contact_id'] ?>">
                                        <button type="submit" name="deleteMessage" class="btn btn-default" title="<?php echo lang('contact::delete-this')?>" onclick="javascript:return confirm('Are you sure you want to delete this message?')"><i class="ion ion-ios-trash-outline"></i> <?php echo lang('contact::delete')?></button>
                                    </form>
                                </div>
                            
                            <!-- /.box-footer -->
                        </div>
                        <!-- /. box -->
                    </div>
                <?php endforeach ?>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!------Mailbox Ends------>


</div>