<div class="wrapper">


    <!------Mailbox Starts------>
    <div style="">
        <!-- Content Header (Page header) -->

        <!--
         <section class="content-header">
             <h1>
                 Read Mail
             </h1>
             <ol class="breadcrumb">
                 <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                 <li class="active">Mailbox</li>
             </ol>
         </section>
 -->
        <!-- Main content -->
        <section class="content">
            <div class="row">


                <!-- /.col -->
                <div class="message_view">
                    <div class="box box-primary">
                       <!-- <div class="box-header with-border">

                            <div class="box-tools pull-right">
                                <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="Previous"><i class="ion ion-chevron-left"></i></a>
                                <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="Next"><i class="ion ion-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.box-header -->

                        <?php foreach($contacts as $contact):?>
                        <div class="box-body add-padding">
                            <div class="mailbox-read-info">
                                <h6 class="details-subject"><?php echo $contact['subject'] ?></h6>
                                <div><b><?php echo lang('contact::from')?></b>: <?php echo $contact['email'] ?>
                                    <span class="mailbox-read-time pull-right"><?php echo $contact['sent_date'] ?>, <?php echo $contact['sent_year'] ?></span></div>
                            </div>
                            <?php endforeach ?>
                            <!-- /.mailbox-read-info -->
                            <div class="mailbox-controls with-border text-center">
                                <div class="btn-group">
                                    <button type="submit" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="<?php echo lang('contact::delete')?>">
                                        <i class="ion ion-ios-trash-outline"></i></button>
                                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="<?php echo lang('contact::reply')?>" onclick="window.location.href='<?php echo url_to_pager('admin-message-reply') ?>?contact_id=<?php echo $contact['contact_id'] ?>'">
                                        <i class="ion ion-reply"></i></button>
                                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="<?php echo lang('contact::forward')?>" onclick="window.location.href='<?php echo url_to_pager('admin-message-forward') ?>?contact_id=<?php echo $contact['contact_id'] ?>'">
                                        <i class="ion ion-forward"></i></button>
                                </div>
                                <!-- /.btn-group -->
                                <!--<button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" title="Print">
                                    <i class="ion fa-print"></i></button>-->
                            </div>
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">


                                <p><?php echo nl2br($contact['message']) ?></p>

                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">


                        </div>
                        <!-- /.box-footer -->
                        <div class="box-footer">
                            <div class="pull-right">
                                <button type="button" class="btn btn-default" title="Reply" onclick="window.location.href='<?php echo url_to_pager('admin-message-reply') ?>?contact_id=<?php echo $contact['contact_id'] ?>'"><i class="ion ion-reply"></i> <?php echo lang('contact::reply')?></button>
                                <button type="button" class="btn btn-default" onclick="window.location.href='<?php echo url_to_pager('admin-message-forward') ?>?contact_id=<?php echo $contact['contact_id'] ?>'"><i class="ion ion-forward"></i> <?php echo lang('contact::forward')?></button>
                            </div>
                            <form method="post" action="delete">
                                <input type="hidden" name="contact_id" value="<?php echo $contact['contact_id'] ?>">
                                <button type="submit" name="deleteMessage" class="btn btn-default" title="<?php echo lang('contact::delete-this')?>" onclick="javascript:return confirm('Are you sure you want to delete this message?')"><i class="ion ion-ios-trash-outline"></i> <?php echo lang('contact::delete')?></button>
                            </form>

                            <!--<button type="button" class="btn btn-default"><i class="fa fa-print"></i> Print</button>-->
                        </div>
                        <!-- /.box-footer -->
                    </div>
                    <!-- /. box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!------Mailbox Ends------>


</div>