<div class="wrapper">
    <div class="wrapper-title"><?php _lang('upgrader::upgrade-system')?></div>
    <div class="wrapper-content">
        <form class="wrapper-form"  action="" method="post">
            <div class="alert alert-info">Provide the database details of the crea8social lite installation</div>

            <?php if($message):?>
                <div class="alert alert-warning"><?php echo $message?></div>
            <?php endif?>
            <div class="form-group">
                <label>Database Host</label>
                <input type="text" class="form-control" name="val[host]"/>
            </div>

            <div class="form-group">
                <label>Database Username</label>
                <input type="text" class="form-control" name="val[username]"/>
            </div>

            <div class="form-group">
                <label>Database Password</label>
                <input type="text" class="form-control" name="val[password]"/>
            </div>

            <div class="form-group">
                <label>Database Name</label>
                <input type="text" class="form-control" name="val[name]"/>
            </div>

            <div class="form-group">
                <label>Database Table Prefix</label>
                <input type="text" class="form-control" name="val[prefix]" value="crea8social_"/>
                <p>If you change it from crea8social_ during installation check your database users table it will look like this yourprefix_users</p>
            </div>

           <p>
               <label class="c-input c-checkbox">
                   <input disabled="disabled" id="radio1" name="val[data][]" value="user" checked type="checkbox">
                   <span class="c-indicator"></span>
                   Move Users
               </label>

           </p>
            <p>
                <label class="c-input c-checkbox">
                    <input id="radio1" name="val[data][]" value="posts" checked type="checkbox">
                    <span class="c-indicator"></span>
                    Move Posts
                </label>

            </p>

            <p>
                <label class="c-input c-checkbox">
                    <input id="radio1" name="val[data][]" value="comments" checked type="checkbox">
                    <span class="c-indicator"></span>
                    Move Comments
                </label>

            </p>


            <!--
            <p>
                <label class="c-input c-checkbox">
                    <input id="radio1" name="val[data][]" value="communities" checked type="checkbox">
                    <span class="c-indicator"></span>
                    Move Communities
                </label>

            </p>
                        <p>
                <label class="c-input c-checkbox">
                    <input id="radio1" name="val[data][]" value="pages" checked type="checkbox">
                    <span class="c-indicator"></span>
                    Move Pages
                </label>

            </p>

            <p>
                <label class="c-input c-checkbox">
                    <input id="radio1" name="val[data][]" value="events" checked type="checkbox">
                    <span class="c-indicator"></span>
                    Move Events
                </label>

            </p>

         <p>
                <label class="c-input c-checkbox">
                    <input id="radio1" name="val[data][]" value="posts" checked type="checkbox">
                    <span class="c-indicator"></span>
                    Move Games
                </label>

            </p>
            <p>
                <label class="c-input c-checkbox">
                    <input id="radio1" name="val[data][]" value="posts" checked type="checkbox">
                    <span class="c-indicator"></span>
                    Move Blogs
                </label>

            </p>
            -->




            <p>
                <label class="c-input c-checkbox">
                    <input id="radio1" name="val[data][]" value="albums" checked type="checkbox">
                    <span class="c-indicator"></span>
                    Move Albums and Photos
                </label>

            </p>

            <p>
                <label class="c-input c-checkbox">
                    <input id="radio1" name="val[data][]" value="connections" checked type="checkbox">
                    <span class="c-indicator"></span>
                    Move Friends & Followers
                </label>

            </p>


            <p>
                <button class="btn btn-info">Start moving</button>
            </p>
        </form>
    </div>
</div>